[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[studio]
enabled = true

[auth]
enabled = true
site_url = "https://helplyai.co"
additional_redirect_urls = ["http://localhost:5173", "http://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
